# Generated by Django 4.2.9 on 2024-02-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemytrip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='desc',
            new_name='delivery',
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='variant',
            field=models.CharField(default='128gb', max_length=10),
        ),
    ]
